name: bridgtl_pinang_maksima_microsite
description: Pinang Maksima Microsite App for PARI.

publish_to: "none"

# Dev
version: 1.0.0+1

# Staging
# version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Stacked Architecture
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  stacked_hooks: ^0.2.1+1
  observable_ish: ^3.0.1
  # Data Models
  freezed_annotation: ^0.14.3
  json_annotation: ^4.4.0
  # Utilities
  dartz: ^0.10.1
  dio: ^4.0.4
  intl: ^0.17.0
  url_launcher: ^6.0.17
  permission_handler: ^8.3.0
  package_info_plus: ^1.3.0
  flutter_device_type: ^0.4.0
  new_version: ^0.2.3
  # Network related
  connectivity: ^3.0.6
  provider: ^6.0.1
  # Database
  shared_preferences: ^2.0.9
  # UI Related
  cupertino_icons: ^1.0.4
  flutter_screenutil: ^5.0.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  camera: ^0.9.4+5
  flutter_exif_rotation: ^0.4.2
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  mask_text_input_formatter: ^2.0.0
  dotted_line: ^3.1.0
  flutter_typeahead: ^3.2.4
  flutter_svg: ^0.23.0+1
  dotted_border: ^2.0.0+1
  glass: ^1.0.1+1
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_web_frame: ^0.0.3
  # Location Related
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  places_service: ^0.1.0+2
  place_picker: ^0.9.20-nullsafety
  # Firebase Related
  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.2
  firebase_messaging: ^11.2.3
  # Any
  exif: ^3.1.1
  file_picker: ^4.5.1
  syncfusion_flutter_pdfviewer: ^20.1.47-beta
  animations: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  # Flavor
  flutter_flavorizr: ^2.1.0
  # Code Generator
  build_runner: ^2.1.5
  stacked_generator: ^0.5.6
  # Data Structure
  freezed: ^0.14.1+2
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200